public with sharing class AOC_21_11_DataProvider {

    public static List<List<Integer>> octoInputTest = new List<List<Integer>>{
        new List<Integer> {5,4,8,3,1,4,3,2,2,3},
        new List<Integer> {2,7,4,5,8,5,4,7,1,1},
        new List<Integer> {5,2,6,4,5,5,6,1,7,3},
        new List<Integer> {6,1,4,1,3,3,6,1,4,6},
        new List<Integer> {6,3,5,7,3,8,5,4,7,8},
        new List<Integer> {4,1,6,7,5,2,4,6,4,5},
        new List<Integer> {2,1,7,6,8,4,1,7,2,1},
        new List<Integer> {6,8,8,2,8,8,1,1,3,4},
        new List<Integer> {4,8,4,6,8,4,8,5,5,4},
        new List<Integer> {5,2,8,3,7,5,1,5,2,6}
    };

    public static List<List<Integer>> octoInput = new List<List<Integer>>{
        new List<Integer> {2,2,3,8,5,1,8,6,1,4},
        new List<Integer> {4,5,5,2,3,8,8,5,5,3},
        new List<Integer> {2,5,6,2,1,2,1,1,4,3},
        new List<Integer> {2,6,6,6,6,8,5,3,3,7},
        new List<Integer> {7,5,7,5,5,1,8,7,8,4},
        new List<Integer> {3,5,7,2,5,3,4,8,7,1},
        new List<Integer> {8,4,1,1,7,1,8,2,8,3},
        new List<Integer> {7,7,4,2,6,6,8,3,8,5},
        new List<Integer> {1,2,3,5,1,3,3,2,3,1},
        new List<Integer> {2,5,4,6,1,6,5,3,4,5}
    };
}